name: simple_calculator
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  ui_kit:
    path: ../ui_kit

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
