name: pr

on:
  pull_request:

jobs:
  pr_check:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: fvm setup
        run: |
          curl -fsSL https://fvm.app/install.sh | bash
          echo "$HOME/fvm/bin" >> $GITHUB_PATH

      - name: dependencies install
        run: |
          npm ci
          fvm use
          fvm flutter pub get
          fvm dart run melos bs

      - name: nx affected
        run: |
          npx nx affected \
            -t format,analyze,test \
            --base="${{ github.event.pull_request.base.sha }}" \
            --head=HEAD \
            --outputStyle=static
